/**
 * Identifies transactional notification kinds for logging and WhatsApp template mapping.
 */
export enum NotificationEvent {
  OTP_EMAIL = 'OTP_EMAIL',
  LICENSE_APPROVED = 'LICENSE_APPROVED',
  LICENSE_REJECTED = 'LICENSE_REJECTED',
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',
  BOOKING_NEW_MERCHANT = 'BOOKING_NEW_MERCHANT',
  BOOKING_ACCEPTED_RENTER = 'BOOKING_ACCEPTED_RENTER',
  BOOKING_REJECTED_RENTER = 'BOOKING_REJECTED_RENTER',
  BOOKING_COMPLETED_RENTER = 'BOOKING_COMPLETED_RENTER',
  BOOKING_CANCELLED_MERCHANT = 'BOOKING_CANCELLED_MERCHANT',
  BOOKING_AUTO_CANCEL_RENTER = 'BOOKING_AUTO_CANCEL_RENTER',
  BOOKING_AUTO_CANCEL_MERCHANT = 'BOOKING_AUTO_CANCEL_MERCHANT',
}
